import { FieldType } from './types';

export type FieldOperators<FieldTypeOrKey> = FieldTypeOrKey extends FieldType.text
	? 'exists' | 'equals' | 'not_equals' | 'in' | 'not_in' | 'contains' | 'not_contains' | 'starts_with' | 'end_with'
	: FieldTypeOrKey extends FieldType.url
	? 'exists' | 'equals' | 'not_equals' | 'in' | 'not_in' | 'contains' | 'not_contains' | 'starts_with' | 'end_with'
	: FieldTypeOrKey extends 'email.address'
	? 'exists' | 'equals' | 'not_equals' | 'in' | 'not_in' | 'contains' | 'not_contains' | 'starts_with' | 'end_with'
	: FieldTypeOrKey extends FieldType.number
	?
			| 'exists'
			| 'equals'
			| 'not_equals'
			| 'in'
			| 'not_in'
			| 'less_than'
			| 'greater_than'
			| 'less_or_equals'
			| 'greater_or_equals'
			| 'between'
	: FieldTypeOrKey extends FieldType.autoNumber
	?
			| 'exists'
			| 'equals'
			| 'not_equals'
			| 'in'
			| 'not_in'
			| 'less_than'
			| 'greater_than'
			| 'less_or_equals'
			| 'greater_or_equals'
			| 'between'
	: FieldTypeOrKey extends FieldType.date
	?
			| 'exists'
			| 'equals'
			| 'not_equals'
			| 'in'
			| 'not_in'
			| 'less_than'
			| 'greater_than'
			| 'less_or_equals'
			| 'greater_or_equals'
			| 'between'
	: FieldTypeOrKey extends FieldType.dateTime
	?
			| 'exists'
			| 'equals'
			| 'not_equals'
			| 'in'
			| 'not_in'
			| 'less_than'
			| 'greater_than'
			| 'less_or_equals'
			| 'greater_or_equals'
			| 'between'
	: FieldTypeOrKey extends 'money.currency'
	?
			| 'exists'
			| 'equals'
			| 'not_equals'
			| 'in'
			| 'not_in'
			| 'less_than'
			| 'greater_than'
			| 'less_or_equals'
			| 'greater_or_equals'
			| 'between'
	: FieldTypeOrKey extends 'money.value'
	?
			| 'exists'
			| 'equals'
			| 'not_equals'
			| 'in'
			| 'not_in'
			| 'less_than'
			| 'greater_than'
			| 'less_or_equals'
			| 'greater_or_equals'
			| 'between'
	: FieldTypeOrKey extends FieldType.boolean
	? 'exists' | 'equals' | 'not_equals'
	: FieldTypeOrKey extends 'address.country'
	? 'exists' | 'equals' | 'not_equals'
	: FieldTypeOrKey extends 'address.state'
	? 'exists' | 'equals' | 'not_equals' | 'in' | 'not_in'
	: FieldTypeOrKey extends 'address.city'
	? 'exists' | 'equals' | 'not_equals' | 'in' | 'not_in' | 'contains' | 'not_contains' | 'starts_with' | 'end_with'
	: FieldTypeOrKey extends 'address.district'
	? 'exists' | 'equals' | 'not_equals' | 'in' | 'not_in'
	: FieldTypeOrKey extends 'address.place'
	? 'exists' | 'equals' | 'not_equals' | 'contains'
	: FieldTypeOrKey extends 'address.number'
	? 'exists' | 'equals' | 'not_equals'
	: FieldTypeOrKey extends 'address.postalCode'
	? 'exists' | 'equals' | 'not_equals' | 'contains'
	: FieldTypeOrKey extends 'address.complement'
	? 'exists' | 'equals' | 'not_equals' | 'contains'
	: FieldTypeOrKey extends 'address.geolocation.0'
	?
			| 'exists'
			| 'equals'
			| 'not_equals'
			| 'in'
			| 'not_in'
			| 'less_than'
			| 'greater_than'
			| 'less_or_equals'
			| 'greater_or_equals'
			| 'between'
	: FieldTypeOrKey extends 'address.geolocation.1'
	?
			| 'exists'
			| 'equals'
			| 'not_equals'
			| 'in'
			| 'not_in'
			| 'less_than'
			| 'greater_than'
			| 'less_or_equals'
			| 'greater_or_equals'
			| 'between'
	: FieldTypeOrKey extends 'personName.first'
	? 'exists' | 'equals' | 'not_equals' | 'contains' | 'not_contains' | 'starts_with' | 'end_with'
	: FieldTypeOrKey extends 'personName.last'
	? 'exists' | 'equals' | 'not_equals' | 'contains' | 'not_contains' | 'starts_with' | 'end_with'
	: FieldTypeOrKey extends 'personName.full'
	? 'exists' | 'equals' | 'not_equals' | 'contains' | 'not_contains' | 'starts_with' | 'end_with'
	: FieldTypeOrKey extends 'phone.phoneNumber'
	? 'exists' | 'equals' | 'not_equals' | 'in' | 'not_in' | 'contains' | 'not_contains' | 'starts_with' | 'end_with'
	: FieldTypeOrKey extends 'phone.countryCode'
	? 'exists' | 'equals' | 'not_equals' | 'in' | 'not_in'
	: FieldTypeOrKey extends FieldType.picklist
	? 'exists' | 'equals' | 'not_equals' | 'in' | 'not_in'
	: FieldTypeOrKey extends FieldType.lookup
	? 'exists'
	: FieldTypeOrKey extends 'lookup._id'
	? 'exists' | 'equals' | 'not_equals' | 'in' | 'not_in'
	: FieldTypeOrKey extends FieldType.encrypted
	? 'exists' | 'equals' | 'not_equals'
	: FieldTypeOrKey extends 'filter.conditions'
	? 'exists'
	: FieldTypeOrKey extends FieldType.filter
	? 'exists'
	: FieldTypeOrKey extends FieldType.richText
	? 'exists' | 'contains'
	: FieldTypeOrKey extends FieldType.file
	? 'exists'
	: FieldTypeOrKey extends FieldType.percentage
	? 'exists' | 'equals' | 'not_equals' | 'less_than' | 'greater_than' | 'less_or_equals' | 'greater_or_equals' | 'between'
	: never;
