type OperatorType =
	| 'text'
	| 'url'
	| 'email.address'
	| 'number'
	| 'autoNumber'
	| 'date'
	| 'dateTime'
	| 'money.currency'
	| 'money.value'
	| 'boolean'
	| 'address.country'
	| 'address.state'
	| 'address.city'
	| 'address.district'
	| 'address.place'
	| 'address.number'
	| 'address.postalCode'
	| 'address.complement'
	| 'address.geolocation.0'
	| 'address.geolocation.1'
	| 'personName.first'
	| 'personName.last'
	| 'personName.full'
	| 'phone.phoneNumber'
	| 'phone.countryCode'
	| 'picklist'
	| 'lookup'
	| 'lookup._id'
	| 'encrypted'
	| 'filter.conditions'
	| 'filter'
	| 'richText'
	| 'file'
	| 'percentage'
	| 'ObjectId'
	| 'composite';

export type FieldOperators<T extends OperatorType> = T extends 'text'
	? 'exists' | 'equals' | 'not_equals' | 'in' | 'not_in' | 'contains' | 'not_contains' | 'starts_with' | 'end_with'
	: T extends 'url'
	? 'exists' | 'equals' | 'not_equals' | 'in' | 'not_in' | 'contains' | 'not_contains' | 'starts_with' | 'end_with'
	: T extends 'email.address'
	? 'exists' | 'equals' | 'not_equals' | 'in' | 'not_in' | 'contains' | 'not_contains' | 'starts_with' | 'end_with'
	: T extends 'number'
	?
			| 'exists'
			| 'equals'
			| 'not_equals'
			| 'in'
			| 'not_in'
			| 'less_than'
			| 'greater_than'
			| 'less_or_equals'
			| 'greater_or_equals'
			| 'between'
	: T extends 'autoNumber'
	?
			| 'exists'
			| 'equals'
			| 'not_equals'
			| 'in'
			| 'not_in'
			| 'less_than'
			| 'greater_than'
			| 'less_or_equals'
			| 'greater_or_equals'
			| 'between'
	: T extends 'date'
	?
			| 'exists'
			| 'equals'
			| 'not_equals'
			| 'in'
			| 'not_in'
			| 'less_than'
			| 'greater_than'
			| 'less_or_equals'
			| 'greater_or_equals'
			| 'between'
	: T extends 'dateTime'
	?
			| 'exists'
			| 'equals'
			| 'not_equals'
			| 'in'
			| 'not_in'
			| 'less_than'
			| 'greater_than'
			| 'less_or_equals'
			| 'greater_or_equals'
			| 'between'
	: T extends 'money.currency'
	?
			| 'exists'
			| 'equals'
			| 'not_equals'
			| 'in'
			| 'not_in'
			| 'less_than'
			| 'greater_than'
			| 'less_or_equals'
			| 'greater_or_equals'
			| 'between'
	: T extends 'money.value'
	?
			| 'exists'
			| 'equals'
			| 'not_equals'
			| 'in'
			| 'not_in'
			| 'less_than'
			| 'greater_than'
			| 'less_or_equals'
			| 'greater_or_equals'
			| 'between'
	: T extends 'boolean'
	? 'exists' | 'equals' | 'not_equals'
	: T extends 'address.country'
	? 'exists' | 'equals' | 'not_equals'
	: T extends 'address.state'
	? 'exists' | 'equals' | 'not_equals' | 'in' | 'not_in'
	: T extends 'address.city'
	? 'exists' | 'equals' | 'not_equals' | 'in' | 'not_in' | 'contains' | 'not_contains' | 'starts_with' | 'end_with'
	: T extends 'address.district'
	? 'exists' | 'equals' | 'not_equals' | 'in' | 'not_in'
	: T extends 'address.place'
	? 'exists' | 'equals' | 'not_equals' | 'contains'
	: T extends 'address.number'
	? 'exists' | 'equals' | 'not_equals'
	: T extends 'address.postalCode'
	? 'exists' | 'equals' | 'not_equals' | 'contains'
	: T extends 'address.complement'
	? 'exists' | 'equals' | 'not_equals' | 'contains'
	: T extends 'address.geolocation.0'
	?
			| 'exists'
			| 'equals'
			| 'not_equals'
			| 'in'
			| 'not_in'
			| 'less_than'
			| 'greater_than'
			| 'less_or_equals'
			| 'greater_or_equals'
			| 'between'
	: T extends 'address.geolocation.1'
	?
			| 'exists'
			| 'equals'
			| 'not_equals'
			| 'in'
			| 'not_in'
			| 'less_than'
			| 'greater_than'
			| 'less_or_equals'
			| 'greater_or_equals'
			| 'between'
	: T extends 'personName.first'
	? 'exists' | 'equals' | 'not_equals' | 'contains' | 'not_contains' | 'starts_with' | 'end_with'
	: T extends 'personName.last'
	? 'exists' | 'equals' | 'not_equals' | 'contains' | 'not_contains' | 'starts_with' | 'end_with'
	: T extends 'personName.full'
	? 'exists' | 'equals' | 'not_equals' | 'contains' | 'not_contains' | 'starts_with' | 'end_with'
	: T extends 'phone.phoneNumber'
	? 'exists' | 'equals' | 'not_equals' | 'in' | 'not_in' | 'contains' | 'not_contains' | 'starts_with' | 'end_with'
	: T extends 'phone.countryCode'
	? 'exists' | 'equals' | 'not_equals' | 'in' | 'not_in'
	: T extends 'picklist'
	? 'exists' | 'equals' | 'not_equals' | 'in' | 'not_in'
	: T extends 'lookup'
	? 'exists'
	: T extends 'lookup._id'
	? 'exists' | 'equals' | 'not_equals' | 'in' | 'not_in'
	: T extends 'encrypted'
	? 'exists' | 'equals' | 'not_equals'
	: T extends 'filter.conditions'
	? 'exists'
	: T extends 'filter'
	? 'exists'
	: T extends 'richText'
	? 'exists' | 'contains'
	: T extends 'file'
	? 'exists'
	: T extends 'percentage'
	? 'exists' | 'equals' | 'not_equals' | 'less_than' | 'greater_than' | 'less_or_equals' | 'greater_or_equals' | 'between'
	: T extends 'ObjectId'
	? 'exists' | 'equals' | 'not_equals'
	: T extends 'composite'
	? 'exists' | 'equals' | 'not_equals'
	: never;
